server:
 port: 8880

spring:
 application:
  name: LabSystem
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/labsystem
  username: root
  password: dinpper
 mail:
  host: smtp.qq.com
  port: 465
  username: 1772775873@qq.com
  password: sirebdlcvyoacejc
  protocol: smtp
  default-encoding: UTF-8
  properties:
    mail:
      smtp:
       auth: true
       starttls.enable: true
       ssl.enable: true

mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.example.labSystem.domain


xxl:
 job:
  # 调度中心的地址，多个地址用逗号分隔
  admin:
   addresses: http://127.0.0.1:8888/xxl-job-admin  # 调度中心的 URL
   accessToken: default_token
  # 执行器配置
  executor:
   appname: xxl-job-executor-sample         # 执行器名称，必须与调度中心中配置的一致
   address:  # 如果没有地址，可以不配置，默认不注册到调度中心
   ip: 127.0.0.1                     # 执行器的 IP 地址，默认是本机 IP
   port: 9999                        # 执行器的端口
   logpath: /data/applogs/xxl-job/logs            # 执行器的日志文件路径
   logretentiondays: -1             # 日志保留天数





logging:
 level:
  root: INFO
  org.mybatis: DEBUG
  com.example.labSystem: DEBUG

#  username: 1772775873@qq.com
#  password: sirebdlcvyoacejc
#  username: 2434714918@qq.com
#  password: ysekssfshlswecgi