server:
 port: 8080

spring:
 application:
  name: LabSystem
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/labsystem
  username: root
  password: dinpper

mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.example.labSystem.domain





logging:
 level:
  root: INFO
  org.mybatis: DEBUG
  com.example.labSystem: DEBUG

