server:
 port: 8080

spring:
 application:
  name: LabSystem
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/labsystem
  username: root
  password: dinpper
 mail:
  host: smtp.qq.com
  port: 465
  username: 2434714918@qq.com
  password: ysekssfshlswecgi
  protocol: smtp
  default-encoding: UTF-8
  properties:
    mail:
      smtp:
       auth: true
       starttls.enable: true
       ssl.enable: true

mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.example.labSystem.domain





logging:
 level:
  root: INFO
  org.mybatis: DEBUG
  com.example.labSystem: DEBUG

#  username: 1772775873@qq.com
#  password: sirebdlcvyoacejc